### PR TITLE
Changed some bg colors and font colors

### PR DESCRIPTION
**Pull request by PawanKolhe**
made the "Footer" look a little better, and made the "Milestone" section bg darker.

### CODE REVIEW

**Comment by yvtheja** [comment]
@PawanKolhe , Great work, but I don't recommend the changes in UI or UX ! Please look at the issues I have filed, select one them and ask me to get it assigned to you and work on them.

**Comment by yvtheja** [comment]
@PawanKolhe, pick some small issues from the list and create 4 PR's, you will get a T-Shirt !! :P

https://github.com/ythej/acm-nit-surat/issues

**Comment by PawanKolhe** [comment]
I would like to work on "Flat icons for all events."
Seems like my thing :)

**Comment by yvtheja** [comment]
@PawanKolhe , reply on the issue that you are working !!

**Pull request closed without merging**
